name: Flutter Nightly Build
run-name: "rustdesk-custom #${{ github.run_number }} by @${{ github.actor }}"

on:
  # 仅手动触发，已禁用定时构建
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      upload-tag:
        description: "自定义 Release Tag"
        required: false
        default: "nightly"

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "${{ github.event.inputs.upload-tag || 'nightly' }}"
