name: Flutter Nightly Build
run-name: "rustdesk-custom #${{ github.run_number }} by @${{ github.actor }}"

on:
  workflow_dispatch:
    inputs:
      upload-tag:
        description: "自定义 Release Tag"
        required: false
        default: "nightly"

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "${{ github.event.inputs.upload-tag || 'nightly' }}"
