name: Full Flutter CI

on:
  workflow_dispatch:
  # 已禁用自动触发
  # pull_request:
  #   paths-ignore:
  #   - "docs/**"
  #   - "README.md"
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - ".github/**"
  #     - "docs/**"
  #     - "README.md"
  #     - "res/**"
  #     - "appimage/**"
  #     - "flatpak/**"

jobs:
  run-ci:
    uses: ./.github/workflows/flutter-build.yml
    with:
      upload-artifact: false
